<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude([
        'config',
        'bootstrap',
        'storage',
        'vendor',
    ]);

$config = new PhpCsFixer\Config();

return $config->setRules([
    '@Symfony' => true,
    '@PSR1' => true,
    '@PSR2' => true,
    '@PSR12' => true,
    '@PER-CS' => true,
    'php_unit_method_casing' => ['case' => 'camel_case'],
    'void_return' => true,
    'concat_space' => ['spacing' => 'one'],
    'no_empty_phpdoc' => true,
    'phpdoc_add_missing_param_annotation' => ['only_untyped' => false],
    'phpdoc_indent' => true,
    'blank_line_before_statement' => ['statements' => [
        'break',
        'case',
        'continue',
        'declare',
        'do',
        'exit',
        'for',
        'foreach',
        'goto',
        'if',
        'include',
        'include_once',
        'phpdoc',
        'require',
        'require_once',
        'return',
        'switch',
        'throw',
        'try',
        'while',
        'yield',
        'yield_from'
    ]],
    'no_trailing_comma_in_singleline' => true,
    'phpdoc_to_comment' => false,
    'align_multiline_comment' => false,
    'no_extra_blank_lines' => ['tokens' => [
        'attribute',
        'break',
        'case',
        'continue',
        'curly_brace_block',
        'default',
        'extra',
        'parenthesis_brace_block',
        'return',
        'square_brace_block',
        'switch',
        'throw',
        'use',
    ]],
    'trim_array_spaces' => true,
    'normalize_index_brace' => true,
    'phpdoc_var_annotation_correct_order' => true,
    'phpdoc_align' => true,
    'phpdoc_types' => true,
    'phpdoc_trim' => true,
    'phpdoc_order' => true,
    'phpdoc_summary' => true,
    'phpdoc_single_line_var_spacing' => true,
    'phpdoc_separation' => true,
    'no_blank_lines_after_phpdoc' => true,
    'return_assignment' => true,
    'no_whitespace_in_blank_line' => true,
    'array_syntax' => ['syntax' => 'short'],
    'array_indentation' => true,
    'no_multiline_whitespace_around_double_arrow' => true,
    'php_unit_test_annotation' => ['style' => 'prefix'],
    'single_blank_line_at_eof' => true,
    'multiline_comment_opening_closing' => true,
    'phpdoc_line_span' => ['method' => 'single'],
    'no_unused_imports' => true,
    'ordered_imports' => true,
    'type_declaration_spaces' => true,
    'no_whitespace_before_comma_in_array' => true,
    'no_singleline_whitespace_before_semicolons' => true,
    'no_useless_sprintf' => true,
    'single_line_comment_spacing' => true,
    'explicit_indirect_variable' => true,
    'cast_spaces' => ['space' => 'single'],
    'binary_operator_spaces' => true,
    'method_chaining_indentation' => true,
    'multiline_whitespace_before_semicolons' => [
        'strategy' => 'no_multi_line'
    ],
    'single_line_empty_body' => true,
    'function_declaration' => [
        'closure_function_spacing' => 'one',
        'closure_fn_spacing' => 'none',
    ],
    'attribute_empty_parentheses' => true,
    'single_line_throw' => false,
])->setFinder($finder)->setRiskyAllowed(true);
